title: PEAC
description: Perception Emulated Actor Critic in Crowd Scenario Navigation
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
head_scripts:
  - <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  - <script id="MathJax-script" async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
